= Exercise: COVID Testing
:includedir: ../../../includes
:source-highlighter: rouge
:stem:
:toc: left

++++
include::{includedir}/navigation.html[]
++++

== Background

The covid_test


== Instructions

Examine the updated link:covid_testing.py[source code] and complete the
following steps:

1. One of your colleagues has modified the data collection program to store the
test results in a list. But they have asked for your help in writing the
function to save the data. Fill in that function marked with a TODO. (5 points) 

2. In no less than 150 words please describe what some potential problems or
pitfalls might be encountered with this data processing pipeline. For
example, how resilient or adaptable is the format of the data file? What could be
done to better describe the contents of the file? Could another
data format work better? What problems might there be with how the data is sent off
each night? How many people could use this program at the same time? These
questions are just examples, which you may choose to answer, but you can also come up
with your own. Try to think creatively and defensively about how this program
might be used. (5 points)

